#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6

  state_publish_rate: 50 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20

velocity_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  gains:
    joint_a1: { p: 1, d: 0.01, i: 1.0 }
    joint_a2: { p: 1, d: 0.01, i: 1.0 }
    joint_a3: { p: 1, d: 0.01, i: 1.0 }
    joint_a4: { p: 1, d: 0.01, i: 1.0 }
    joint_a5: { p: 1, d: 0.01, i: 1.0 }
    joint_a6: { p: 1, d: 0.01, i: 1.0 }
  state_publish_rate: 50
  action_monitor_rate: 20 