joint_limits:
  joint_a1:
    has_position_limits: true
    min_position: -2.9670597283903604
    max_position: 2.9670597283903604
    has_velocity_limits: true
    # max_velocity: 6.283185307179586
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false
  joint_a2:
    has_position_limits: true
    min_position: -3.3161255787892263
    max_position: 0.7853981633974483
    has_velocity_limits: true
    # max_velocity: 5.235987755982989
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false
  joint_a3:
    has_position_limits: true
    min_position: -2.0943951023931953
    max_position: 2.722713633111154
    has_velocity_limits: true
    # max_velocity: 6.283185307179586
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false
  joint_a4:
    has_position_limits: true
    min_position: -3.2288591161895095
    max_position: 3.2288591161895095
    has_velocity_limits: true
    # max_velocity: 6.649704450098396
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false
  joint_a5:
    has_position_limits: true
    min_position: -2.0943951023931953
    max_position: 2.0943951023931953
    has_velocity_limits: true
    # max_velocity: 6.771877497737998
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false
  joint_a6:
    has_position_limits: true
    min_position: -6.1086523819801535
    max_position: 6.1086523819801535
    has_velocity_limits: true
    # max_velocity: 10.733774899765127
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_effort_limits: false